import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const fontPath = join(
  __dirname,
  '../../../node_modules/@fontsource/press-start-2p/files/press-start-2p-latin-400-normal.woff2'
)

const outPath = join(__dirname, '../src/lib/font.ts')

const fontData = await readFile(fontPath)
const base64 = fontData.toString('base64')

await mkdir(dirname(outPath), { recursive: true })
await writeFile(
  outPath,
  `// Auto-generated by scripts/generate-font.ts — do not edit manually\n` +
  `export const PRESS_START_2P_WOFF2_BASE64 = '${base64}'\n`
)

console.log(`Font encoded (${fontData.byteLength} bytes) → src/lib/font.ts`)
