import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = `${__dirname}/../src/lib/font.ts`

async function encodeFont(filePath: string): Promise<string> {
  const data = await readFile(filePath)
  console.log(`  ${filePath.split('/').pop()} → ${data.byteLength} bytes`)
  return data.toString('base64')
}

await mkdir(dirname(outPath), { recursive: true })

const pressStart2p = await encodeFont(
  fileURLToPath(import.meta.resolve('@fontsource/press-start-2p/files/press-start-2p-latin-400-normal.woff2'))
)
const ibmPlexMono = await encodeFont(
  join(__dirname, '../assets/IBMPlexMono-Regular.ttf')
)

await writeFile(
  outPath,
  `// Auto-generated by scripts/generate-font.ts — do not edit manually\n` +
  `export const PRESS_START_2P_WOFF2_BASE64 = '${pressStart2p}'\n` +
  `export const IBM_PLEX_MONO_TTF_BASE64 = '${ibmPlexMono}'\n`
)

console.log(`Fonts written → src/lib/font.ts`)
