name = "badge-kit"
main = "src/index.ts"
compatibility_date = "2026-05-29"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "badges.is-pinoy.dev/*"
zone_name = "is-pinoy.dev"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
