name = "tools-analytics"
main = "index.ts"
compatibility_date = "2026-05-27"
workers_dev = false
preview_urls = false

[triggers]
crons = ["0 1 * * *"]

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "analytics-db"
database_id = "f0b338c1-b5d4-48db-8b42-0435a24ef430"
migrations_dir = "migrations"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
