export const RESERVED_SUBDOMAINS = [
  "www",
  "api",
  "admin",
  "auth",
  "community",
  "app",
  "dashboard",
  "console",
  "cdn",
  "status",
  "dev",
  "staging",
  "beta",
  "oss",
  "showcase",
  "blog",
  "docs",
  "forum",
  // Platform tooling namespace — /_tools/* paths are intercepted by Cloudflare Workers
  "_tools",
];
